In [1]:
#time

In [2]:
import numpy as np

In [3]:
numpy_array = np.arange(0, 1000000)
python_list = range(1000000)

In [6]:
print "python list"
time = %timeit -r 1 -o sum(python_list)
print time.all_runs[0]/time.loops 

python list
100 loops, best of 1: 8.69 ms per loop
0.00868973016739


In [5]:
print "\n" + "numpy array"
time = %timeit -r 1 -o np.sum(numpy_array)
print time.all_runs[0]/time.loops


numpy array
1000 loops, best of 1: 739 µs per loop
0.000739181995392


In [13]:
print "\n" + "numpy array -- standard library sum"
time = %timeit -r 1 -o sum(numpy_array)
print time.all_runs[0]/time.loops


numpy array -- standard library sum
10 loops, best of 1: 88.9 ms per loop
0.0888759851456


In [11]:
print "\n" + "python list -- numpy library sum"
time = %timeit -r 1 -o np.sum(python_list)
print time.all_runs[0]/time.loops


python list -- numpy library sum
10 loops, best of 1: 50.7 ms per loop
0.0506631851196


In [ ]:
#types

In [34]:
my_lst_ndarray = np.array([[1], [2], [3], [4], [5]])
my_tuple_ndarray = np.array((1, 2, 3, 4, 5), np.int32)

print my_lst_ndarray.dtype
print my_tuple_ndarray.dtype

my_lst_ndarray

int64
int32


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [20]:
print my_lst_ndarray.shape
print my_tuple_ndarray.shape

(5, 1)
(5,)


In [22]:
my_lst_ndarray2 = np.array(["1", 2, 3, "10", 5])
print my_lst_ndarray2.dtype
my_lst_ndarray2

|S2


array(['1', '2', '3', '10', '5'], 
      dtype='|S2')

In [26]:
my_lst_ndarray3 = np.array([1, 2, 3, 10.0, 5]) 
print my_lst_ndarray3.dtype
my_lst_ndarray3

float64


array([  1.,   2.,   3.,  10.,   5.])

In [27]:
myf2(lambda x: x)

In [28]:
def myf2(x):
    return x

In [30]:
myf2(2)

2

In [31]:
myf3 = myf(lambda x: x)

In [32]:
[1,3.14,myf3,[7,11]]

[1, 3.14, <function __main__.<lambda>>, [7, 11]]

In [ ]:
# element-wise

In [35]:
[1, 2, 3] + [3, 2, 1]

[1, 2, 3, 3, 2, 1]

In [36]:
np.array([1, 2, 3]) + np.array([3, 2, 1])

array([4, 4, 4])

In [46]:
first_arr = np.array([[1, 2], [3, 4]]) 
second_arr = np.array([[5, 6], [7, 8]]) 
first_arr * second_arr
first_arr.dot(second_arr)

"5"*54

'555555555555555555555555555555555555555555555555555555'

In [50]:
first_arr % 4

array([[1, 2],
       [3, 0]])

In [48]:
first_arr - np.array([4])

array([[-3, -2],
       [-1,  0]])

In [12]:
# broadcasting

In [56]:
#a = np.array([[10], [-10]]) 
a = np.array([[10,-10]]) 
b = np.array([[[4,4], [4,4], [4,4]], [[4,4], [4,4], [4,4]]]) 

print b
print a.shape, b.shape 
print "\n"
print a + b

[[[4 4]
  [4 4]
  [4 4]]

 [[4 4]
  [4 4]
  [4 4]]]
(1, 2) (2, 3, 2)


[[[14 -6]
  [14 -6]
  [14 -6]]

 [[14 -6]
  [14 -6]
  [14 -6]]]


In [ ]:
# matrix convenience functions

In [78]:
np.zeros((3,4))
np.ones((3,4))
np.identity((3))
np.random.rand(3,2,2)
np.random.randn(3,2,2)
np.arange(10,12,.2)
np.linspace(1,10,30)

array([  1.        ,   1.31034483,   1.62068966,   1.93103448,
         2.24137931,   2.55172414,   2.86206897,   3.17241379,
         3.48275862,   3.79310345,   4.10344828,   4.4137931 ,
         4.72413793,   5.03448276,   5.34482759,   5.65517241,
         5.96551724,   6.27586207,   6.5862069 ,   6.89655172,
         7.20689655,   7.51724138,   7.82758621,   8.13793103,
         8.44827586,   8.75862069,   9.06896552,   9.37931034,
         9.68965517,  10.        ])

In [ ]:
#indexing? .iloc, .loc, .ix, .ax

In [87]:
range_arr = np.arange(0, 20, 1).reshape(5, 4)
print range_arr
range_arr[1:2,:2] = 0
range_arr

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([[ 0,  1,  2,  3],
       [ 0,  0,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
# np ndarray methods

In [ ]:
# merge, join, concatentate